# Generated by Django 4.2.7 on 2026-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='userpet',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='图片URL'),
        ),
    ]
